[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list_app = "BwLPzhxWQf2Bqvz3rfXpGh5ayu6reNRZTJwryKsj5rKq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hkv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
